#ifndef COLLISIONTYPES
#define COLLISIONTYPES

#define COLLISION_UNKNOWN		0
#define COLLISION_WALL			1
#define COLLISION_STAIR			2
#define COLLISION_HACKER		3
#define COLLISION_GUARD			4
#define COLLISION_TARGET		5
#define COLLISION_EMPTY			6
#define COLLISION_SOLID			7

#define MSG_ROOMCHANGE			8

#endif
