#ifndef COLLISIONTYPES
#define COLLISIONTYPES

#define COLLISION_UNKNOWN				0
#define COLLISION_WALL					1
#define COLLISION_STAIR					2
#define COLLISION_HACKER				3
#define COLLISION_GUARD					4
#define COLLISION_TARGET				5
#define COLLISION_EMPTY					6
#define COLLISION_SOLID					7
#define COLLISION_ICE 					10007
#define COLLISION_BELTUP 				10008
#define COLLISION_BELTRIGHT 			10009
#define COLLISION_BELTDOWN 				10010
#define COLLISION_BELTLEFT 				10011
#define COLLISION_PU_INVISIBLE			10012
#define COLLISION_PU_SPEEDUP			10013
#define COLLISION_PU_SPEEDDOWN			10014
#define COLLISION_BELTRIGHT_TILE		9
#define COLLISION_BELTLEFT_TILE		    10

#define MSG_ROOMCHANGE					8
#define TILE_BELT_LEFT					1
#define TILE_BELT_RIGHT					2

#endif
